[tools]
wally = "UpliftGames/wally@0.3.2"
rojo = "rojo-rbx/rojo@7.4.3"
stylua = "johnnymorganz/stylua@0.20.0"
selene = "kampfkarren/selene@0.27.1"
luau-lsp = "johnnymorganz/luau-lsp@1.32.1"
lune = "lune-org/lune@0.8.6"
rbxcloud = "Sleitnick/rbxcloud@0.14.0"